"use client";
import {useEffect,useState} from "react";
import {Gate,Card,SectionHead,api} from "../../components/jarvis";
const SUBJECTS=["Mathematics","Physics","Chemistry"],ACTIVITIES=["Module Practice","JEE Main PYQ","JEE Advanced PYQ","Concept Drill","Revision + Questions","Error Book","Mixed Practice"],TAGS=["None / Smooth","🔴 Calculation Error","🟡 Concept Gap","🟢 Formula Forgot","🟣 Silly Mistake","⏱️ Took Too Long","🎯 Question Selection Issue"];
function parseQuestions(v:string){const out:number[]=[];for(const p of (v||"").split(",")){const x=p.trim();if(x.includes("-")){const [a,b]=x.split("-").map(Number);if(Number.isFinite(a)&&Number.isFinite(b))for(let i=a;i<=b;i++)out.push(i)}else if(/^\\d+$/.test(x))out.push(Number(x))}return [...new Set(out)]}
export default function Practice(){
 const [tab,setTab]=useState("Log 1: Module Config"),[data,setData]=useState<any>({sessions:[],plans:[]}),[session,setSession]=useState<any>(null),[idx,setIdx]=useState(0),[start,setStart]=useState(0),[qStart,setQStart]=useState(0),[diagnosis,setDiagnosis]=useState(""),[busy,setBusy]=useState(false);
 const [subject,setSubject]=useState("Mathematics"),[chapter,setChapter]=useState(""),[ex,setEx]=useState(["1-10","","","",""]),[aiSubject,setAiSubject]=useState("Physics"),[aiChapter,setAiChapter]=useState(""),[instruction,setInstruction]=useState("5 conceptual MCQs banao"),[material,setMaterial]=useState("");
 const [weekStart,setWeekStart]=useState(new Date().toISOString().slice(0,10)),[slotCount,setSlotCount]=useState(2),[duration,setDuration]=useState(120),[days,setDays]=useState(["Monday","Wednesday","Friday"]),[activity,setActivity]=useState(ACTIVITIES[0]);
 async function load(){const x=await api("/api/module/practice");setData(x&&typeof x==="object"?x:{sessions:[],plans:[]})}useEffect(()=>{load().catch(()=>{})},[]);
 async function persist(x:any){setData(x);await api("/api/module/practice",{method:"PUT",body:JSON.stringify({data:x})})}
 function startManual(){const qs:any[]=[];ex.forEach((raw,i)=>parseQuestions(raw).forEach(n=>qs.push({exercise:"Ex-"+(i+1),q_no:n,status:"Pending",problem_note:""})));if(!chapter.trim()||!qs.length)return;setSession({subject,chapter:chapter.trim(),mode:"Manual Multi-Exercise",questions:qs,logs:[]});setIdx(0);setStart(Date.now());setQStart(Date.now());setTab("Log 3: Active Practice")}
 async function finish(s:any){const logs=s.logs||[],solved=logs.filter((x:any)=>x.status==="Solved").length,wrong=logs.filter((x:any)=>x.status==="Stuck").length,skipped=logs.filter((x:any)=>x.status==="Skipped").length,attempted=solved+wrong,accuracy=attempted?Math.round(solved/attempted*1000)/10:0;const summary={type:"practice_session",id:"practice-session:"+Date.now(),date:new Date().toISOString().slice(0,10),subject:s.subject,chapter:s.chapter,mode:s.mode,total:logs.length,solved,wrong,skipped,accuracy,duration_seconds:Math.floor((Date.now()-start)/1000),logs};await persist({...data,sessions:[summary,...(data.sessions||[])]});setSession(null);setTab("Log 4: Session Analysis")}
 async function submit(status:string){if(!session)return;const tag=(document.getElementById("practice-tag") as HTMLSelectElement)?.value||"None / Smooth",note=(document.getElementById("practice-note") as HTMLInputElement)?.value||"",qs=[...session.questions],q={...qs[idx],status,problem_note:(tag+" | "+note).replace(/^\\s*\\|\\s*$/,""),time_seconds:Math.floor((Date.now()-qStart)/1000)};qs[idx]=q;const ns={...session,questions:qs,logs:[...(session.logs||[]),q]};if(idx+1>=qs.length)return finish(ns);setSession(ns);setIdx(idx+1);setQStart(Date.now())}
 async function diagnose(){setBusy(true);try{const s=data.sessions?.[0];if(!s)return;const x=await api("/api/ai/chat",{method:"POST",body:JSON.stringify({message:"Analyze this completed JEE practice session. DATA: "+JSON.stringify(s)+". Give what went well, important mistakes, root causes, what to revise, and tomorrow's correction drill."})});setDiagnosis(x.answer||"")}catch(e:any){setDiagnosis(e.message||"AI failed")}finally{setBusy(false)}}
 async function quiz(){setBusy(true);try{const x=await api("/api/ai/chat",{method:"POST",body:JSON.stringify({message:"You are an expert JEE Main + Advanced tutor. Subject="+aiSubject+", chapter="+aiChapter+". "+instruction+". Return exactly 5 MCQs as JSON with a questions array; each item question, options[A-D], correct_index, topic, explanation. MATERIAL:"+material.slice(0,12000)})});const raw=String(x.answer||"").replace(new RegExp(String.fromCharCode(96)+"{3}json|"+String.fromCharCode(96)+"{3}","g"),"").trim();let d:any;try{d=JSON.parse(raw)}catch{d={questions:[]}}if(d.questions?.length){const qs=d.questions.map((q:any,i:number)=>({exercise:"AI Quiz",q_no:i+1,question_text:q.question,options:q.options,correct_ans:q.options?.[q.correct_index||0]||"",concept:q.topic||"General",explanation:q.explanation||"",status:"Pending",problem_note:""}));setSession({subject:aiSubject,chapter:aiChapter||"AI Quiz",mode:"AI Quiz",questions:qs,logs:[]});setIdx(0);setStart(Date.now());setQStart(Date.now());setTab("Log 3: Active Practice")}}catch(e:any){alert(e.message||"AI quiz failed")}finally{setBusy(false)}}
 function readMaterial(f:File){const r=new FileReader();r.onload=()=>setMaterial(String(r.result||""));r.readAsText(f)}
 async function saveWeek(){const slots:any[]=[],base=new Date(weekStart+"T00:00:00");for(let d=0;d<7;d++){const date=new Date(base);date.setDate(base.getDate()+d);const day=date.toLocaleDateString("en-US",{weekday:"long"});if(!days.includes(day))continue;for(let i=0;i<slotCount;i++){const st=360+i*duration,en=st+duration;slots.push({id:date.toISOString().slice(0,10)+":"+i,date:date.toISOString().slice(0,10),day,start_min:st,end_min:en,duration_min:duration,time:String(Math.floor(st/60)%24).padStart(2,"0")+":"+String(st%60).padStart(2,"0")+" – "+String(Math.floor(en/60)%24).padStart(2,"0")+":"+String(en%60).padStart(2,"0"),subject,activity,task:activity+" — "+subject,done:false})}}await persist({...data,plans:[{type:"practice_plan",id:"practice-plan:"+Date.now(),week_start:weekStart,created_at:Date.now(),slots},...(data.plans||[]).filter((p:any)=>p.week_start!==weekStart)]})}
 return <Gate title="Practice Drill" subtitle="Ranker Matrix: exercise-wise setup → AI quiz → active arena → diagnosis → weekly practice planner.">
  <div className="tabbar">{["Log 1: Module Config","Log 2: AI Quiz Studio","Log 3: Active Practice","Log 4: Session Analysis","Log 5: Weekly Practice Planner"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
  {tab==="Log 1: Module Config"&&<Card><SectionHead kicker="LOG 1" title="Exercise-wise Practice Setup"/><div className="form-grid"><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{SUBJECTS.map(x=><option key={x}>{x}</option>)}</select></label><label>Chapter<input value={chapter} onChange={e=>setChapter(e.target.value)} placeholder="Sets / Motion in 2D"/></label></div><div className="exercise-grid">{ex.map((v,i)=><label key={i}>Exercise-{i+1}{i===4?" / PYQ":""}<input value={v} onChange={e=>{const a=[...ex];a[i]=e.target.value;setEx(a)}} placeholder="1-10"/></label>)}</div><button className="primary" onClick={startManual}>🚀 Start Practice Session</button></Card>}
  {tab==="Log 2: AI Quiz Studio"&&<Card><SectionHead kicker="LOG 2" title="AI PDF Quiz & Metadata Studio"/><div className="form-grid"><label>Subject<select value={aiSubject} onChange={e=>setAiSubject(e.target.value)}>{SUBJECTS.map(x=><option key={x}>{x}</option>)}</select></label><label>Chapter / Topic<input value={aiChapter} onChange={e=>setAiChapter(e.target.value)}/></label></div><input type="file" accept=".pdf,.txt" onChange={e=>{const f=e.target.files?.[0];if(f)readMaterial(f)}}/><label>AI instruction<input value={instruction} onChange={e=>setInstruction(e.target.value)}/></label><button className="primary" onClick={quiz} disabled={busy}>{busy?"🧠 Generating…":"✨ Generate AI Quiz"}</button><p className="muted">Material context is passed to the tutor for targeted quiz generation.</p></Card>}
  {tab==="Log 3: Active Practice"&&<Card><SectionHead kicker="LOG 3" title="Active Practice Arena"/>{!session?<div className="empty">Log 1 or Log 2 se practice session start karo.</div>:<><div className="stats"><div className="stat-card"><small>Question</small><strong>{idx+1}/{session.questions.length}</strong></div><div className="stat-card"><small>Session Time</small><strong>{Math.floor((Date.now()-start)/60000)}m</strong></div><div className="stat-card"><small>Question Time</small><strong>{Math.floor((Date.now()-qStart)/60000)}m</strong></div></div><h3>🎯 {session.questions[idx]?.exercise} — Q{session.questions[idx]?.q_no}</h3>{session.questions[idx]?.question_text?<p>{session.questions[idx].question_text}</p>:<p className="muted">Solve the question from your module/register, then tag the performance.</p>}<label>Performance diagnosis<select id="practice-tag">{TAGS.map(x=><option key={x}>{x}</option>)}</select></label><label>What went wrong?<input id="practice-note" placeholder="Optional"/></label><div className="action-row"><button className="primary" onClick={()=>submit("Solved")}>✅ Solved</button><button className="secondary" onClick={()=>submit("Skipped")}>⏭️ Skip</button><button className="danger" onClick={()=>submit("Stuck")}>📌 Stuck</button></div></>}</Card>}
  {tab==="Log 4: Session Analysis"&&<Card><SectionHead kicker="LOG 4" title="Performance & Mistake Vault"/>{!data.sessions?.length?<div className="empty">Complete a practice session first.</div>:<><div className="stats"><div className="stat-card"><small>Solved</small><strong>{data.sessions[0].solved}</strong></div><div className="stat-card"><small>Wrong/Stuck</small><strong>{data.sessions[0].wrong}</strong></div><div className="stat-card"><small>Skipped</small><strong>{data.sessions[0].skipped}</strong></div><div className="stat-card"><small>Accuracy</small><strong>{data.sessions[0].accuracy}%</strong></div></div><button className="primary" onClick={diagnose} disabled={busy}>{busy?"Analyzing…":"🤖 Diagnose This Session"}</button>{diagnosis&&<div className="ai-report"><p>{diagnosis}</p></div>}<h3>Saved sessions: {data.sessions.length}</h3>{data.sessions.slice(0,20).map((s:any)=><details className="error-item" key={s.id}><summary>{s.date} · {s.chapter} · {s.accuracy}%</summary><p>Solved {s.solved} · Wrong {s.wrong} · Skipped {s.skipped} · {Math.floor(s.duration_seconds/60)} min</p>{(s.logs||[]).filter((x:any)=>x.status!=="Solved"||x.problem_note).map((x:any)=><p key={x.q_no}>Q{x.q_no} — {x.status} — {x.problem_note} — {x.time_seconds}s</p>)}</details>)}</>}</Card>}
  {tab==="Log 5: Weekly Practice Planner"&&<Card><SectionHead kicker="LOG 5" title="Weekly Practice Planner"/><div className="form-grid"><label>Week starts on<input type="date" value={weekStart} onChange={e=>setWeekStart(e.target.value)}/></label><label>Slots per selected day<input type="number" min="1" max="8" value={slotCount} onChange={e=>setSlotCount(+e.target.value)}/></label><label>Default duration (min)<input type="number" min="15" value={duration} onChange={e=>setDuration(+e.target.value)}/></label><label>Focus<select value={activity} onChange={e=>setActivity(e.target.value)}>{ACTIVITIES.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="action-row">{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map(d=><button className={days.includes(d)?"secondary":"ghost"} onClick={()=>setDays(v=>v.includes(d)?v.filter(x=>x!==d):[...v,d])} key={d}>{d.slice(0,3)}</button>)}</div><button className="primary" onClick={saveWeek}>🚀 Save Entire Week & Sync to Todo</button>{(data.plans||[]).map((p:any)=><details className="error-item" key={p.id}><summary>Week of {p.week_start} · {p.slots?.length||0} slots</summary>{(p.slots||[]).map((s:any)=><p key={s.id}>{s.date} · {s.time} · {s.subject} · {s.activity} · {s.done?"Done":"Pending"}</p>)}</details>)}</Card>}
 </Gate>
}