"use client";
import {useEffect,useRef,useState} from "react";
const API="https://jarivsforme-api.onrender.com";
export default function Home(){
 const [token,setToken]=useState<string|null>(null),[user,setUser]=useState<any>(null),[d,setD]=useState<any>({hours:0,questions:0,accuracy:0,backlog:0,highBacklog:0,plans:[]});
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[reg,setReg]=useState(false),[err,setErr]=useState("");
 const [msg,setMsg]=useState(""),[answer,setAnswer]=useState(""),[busy,setBusy]=useState(false),[listening,setListening]=useState(false),[planBusy,setPlanBusy]=useState(false);
 const rec=useRef<any>(null);
 useEffect(()=>{const t=localStorage.getItem("jarvis_token");if(t){setToken(t);load(t)}},[]);
 async function req(path:string,opt:any={}){
  const t=token||localStorage.getItem("jarvis_token");
  const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(t?{Authorization:"Bearer "+t}:{}),...(opt.headers||{})}});
  const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.error||"Request failed");return x;
 }
 async function load(t:string){try{const h=await fetch(API+"/api/me",{headers:{Authorization:"Bearer "+t}});if(!h.ok)throw 0;setUser(await h.json());setD(await (await fetch(API+"/api/dashboard",{headers:{Authorization:"Bearer "+t}})).json())}catch{localStorage.removeItem("jarvis_token");setToken(null)}}
 async function auth(){setErr("");try{const x=await req(reg?"/api/auth/register":"/api/auth/login",{method:"POST",body:JSON.stringify(reg?{email,password,name}:{email,password})});localStorage.setItem("jarvis_token",x.token);setToken(x.token);setUser(x.user);load(x.token)}catch(e:any){setErr(e.message)}}
 async function refresh(){try{setD(await req("/api/dashboard"))}catch{}}
 async function log(){try{await req("/api/study/log",{method:"POST",body:JSON.stringify({minutes:30})});await refresh();speak("Thirty minutes logged. Keep going.")}catch(e:any){setErr(e.message)}}
 async function send(text?:string){const q=(text===undefined?msg:text).trim();if(!q||busy)return;setMsg("");setBusy(true);try{const x=await req("/api/ai/chat",{method:"POST",body:JSON.stringify({message:q})});setAnswer(x.answer);speak(x.answer);await refresh()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 async function makePlan(){setPlanBusy(true);try{await req("/api/ai/plan",{method:"POST",body:"{}"});await refresh();speak("Your study plan is ready.")}catch(e:any){setErr(e.message)}finally{setPlanBusy(false)}}
 async function speak(text:string){
  if(typeof window==="undefined")return;
  try{
    const t=localStorage.getItem("jarvis_token");
    const r=await fetch(API+"/api/voice/speak",{method:"POST",headers:{"Content-Type":"application/json",...(t?{Authorization:"Bearer "+t}:{})},body:JSON.stringify({text})});
    if(r.ok){const blob=await r.blob();const audio=new Audio(URL.createObjectURL(blob));await audio.play();return}
  }catch{}
  if(window.speechSynthesis){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.slice(0,1800));u.rate=.98;window.speechSynthesis.speak(u)}
}
 function voice(){const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setErr("Voice input needs Chrome.");return}if(listening){rec.current?.stop();return}const r=new SR();rec.current=r;r.lang="en-IN";r.interimResults=false;r.continuous=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>{setListening(false);setErr("Mic permission or recognition failed.")};r.onresult=(e:any)=>{const t=e.results[0][0].transcript;if(/log (30|thirty) (minutes?|mins?)/i.test(t))log();else send(t)};r.start()}
 if(!token)return <Auth reg={reg} setReg={setReg} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} err={err} auth={auth}/>;
 return <main className="app"><aside className="sidebar"><Brand/><nav>{["Dashboard","AI Mentor","Study Planner","Backlog","Practice","Tests","Error Book","Analytics"].map((x,i)=><button className={i===0?"nav active":"nav"} key={x}>{x}</button>)}</nav><div className="mentor-card"><span className="pulse"/><div><b>JARVIS online</b><small>Voice + AI ready</small></div></div><button className="logout" onClick={()=>{localStorage.removeItem("jarvis_token");location.reload()}}>Log out</button></aside>
 <section className="content"><header className="topbar"><div><span className="eyebrow">JEE COMMAND CENTER</span><h1>Good evening, {user?.name||"warrior"}.</h1><p>Real progress, AI planning and voice commands.</p></div><button className={"voice "+(listening?"listening":"")} onClick={voice}>{listening?"● Listening…":"🎙 Talk to JARVIS"}</button></header>
 {err&&<div className="error">{err}</div>}<section className="hero"><div><span className="tag">TODAY'S MISSION</span><h2>Make today count.</h2><p>{d.plans.length?d.plans.length+" AI study blocks ready.":"Generate a plan from your real progress."}</p></div><div className="hero-actions"><button className="primary" onClick={log}>＋ Log 30 min</button><button className="secondary" onClick={makePlan}>{planBusy?"Generating…":"✦ Generate AI plan"}</button></div></section>
 <div className="stats"><Stat label="Study hours" value={Number(d.hours).toFixed(1)} meta="Last 7 days"/><Stat label="Questions" value={d.questions} meta="Last 7 days"/><Stat label="Accuracy" value={d.accuracy+"%"} meta="Logged questions"/><Stat label="Backlog" value={d.backlog} meta={d.highBacklog+" high priority"}/></div>
 <div className="main-grid"><section className="panel"><Head a="DAILY PLAN" b="Today's study blocks"/>{d.plans.length?d.plans.map((p:any,i:number)=><div className="plan" key={p.id||i}><span className="check">{p.completed?"✓":""}</span><div><small>{p.start_time||"Flexible"} {p.end_time?"– "+p.end_time:""}</small><b>{p.subject} · {p.topic}</b><p>{p.task}</p></div></div>):<div className="empty">No plan yet. Generate one from your real data.</div>}</section>
 <section className="panel"><Head a="AI MENTOR" b="Talk to JARVIS"/><div className="answer">{answer||"Ask what to study, tell me what you completed, or speak your problem."}</div><div className="composer"><textarea value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="e.g. I have 3 hours tonight. What should I study?"/><button className="mic" onClick={voice}>🎙</button></div><button className="primary full" onClick={()=>send()} disabled={busy}>{busy?"JARVIS is thinking…":"Send to JARVIS"}</button></section>
 <section className="panel"><Head a="QUICK ACTIONS" b="Study controls"/><button className="action" onClick={log}>⏱ Log 30 minutes</button><button className="action" onClick={()=>send("Analyze my current JEE progress and tell me my next action.")}>⌁ Analyze my progress</button><button className="action" onClick={()=>send("Give me a focused revision session for my highest priority backlog.")}>↻ Start backlog revision</button><button className="action" onClick={makePlan}>✦ Rebuild today's plan</button></section>
 <section className="panel"><Head a="BACKLOG" b="Needs attention"/><div className="backlog-row"><b>High priority</b><span>{d.highBacklog}</span></div><div className="backlog-row"><b>Total open</b><span>{d.backlog}</span></div><p className="muted">JARVIS uses this data when planning and answering you.</p></section></div><footer>JARVISFORME · Vercel + Render PostgreSQL + OpenAI · Voice ready</footer></section></main>
}
function Brand(){return <div className="brand"><span className="brand-mark">J</span><div><strong>JARVIS</strong><small>FOR ME</small></div></div>}
function Head({a,b}:{a:string;b:string}){return <div className="panel-head"><div><span className="eyebrow">{a}</span><h3>{b}</h3></div><span className="status">LIVE</span></div>}
function Stat({label,value,meta}:{label:string;value:string|number;meta:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{meta}</small></div>}
function Auth(p:any){return <main className="auth-page"><div className="auth-card"><div className="auth-brand"><Brand/></div><span className="eyebrow">PERSONAL JEE MENTOR</span><h1>{p.reg?"Create your JARVIS":"Welcome back"}</h1><p>AI planning, real tracking and voice commands.</p>{p.reg&&<input value={p.name} onChange={(e:any)=>p.setName(e.target.value)} placeholder="Your name"/>}<input value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)} placeholder="Email"/><input type="password" value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)} placeholder="Password (6+ characters)"/>{p.err&&<div className="error">{p.err}</div>}<button className="primary full" onClick={p.auth}>{p.reg?"Create account":"Log in"}</button><button className="switch" onClick={()=>p.setReg(!p.reg)}>{p.reg?"Already have an account? Log in":"New here? Create account"}</button></div></main>}
