"use client";
import Link from "next/link";
import {useEffect,useState,ReactNode} from "react";
export const API="https://jarivsforme-api.onrender.com";
export async function api(path:string, options:any={}){const token=typeof window!=="undefined"?localStorage.getItem("jarvis_token"):"";const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Request failed");return data}
export function Shell({children,title,subtitle}:{children:ReactNode,title?:string,subtitle?:string}){const[user,setUser]=useState<any>(null);useEffect(()=>{if(localStorage.getItem("jarvis_token"))api("/api/me").then(setUser).catch(()=>localStorage.removeItem("jarvis_token"))},[]);const nav=[["Dashboard","/dashboard","⌂"],["AI Tutor","/ai-guru","✦"],["Backlog 360","/backlog","◒"],["Todo","/todo","✓"],["Error Book","/error-book","◇"]];return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/ai-guru"><span className="brand-mark">J</span><span><b>JARVIS</b><small>FOR ME · JEE OS</small></span></Link><div className="side-label">JARVIS COMMAND CENTER</div><nav>{nav.map(([n,h,i])=><Link key={h} href={h}><span>{i}</span>{n}</Link>)}</nav><div className="online"><i/><div><b>JARVIS online</b><small>AI · Voice · Data connected</small></div></div><button className="logout" onClick={()=>{localStorage.removeItem("jarvis_token");location.href="/"}}>Log out</button></aside><main className="main"><header className="mobile-head"><Link className="brand" href="/dashboard"><span className="brand-mark">J</span><b>JARVIS</b></Link></header>{(title||subtitle)&&<div className="page-head"><div><span className="eyebrow">JEE WAR ROOM</span><h1>{title}</h1><p>{subtitle}</p></div><div className="user-pill">● {user?.name||"Student"}</div></div>}{children}</main></div>}
export function Auth(){const[reg,setReg]=useState(false),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);async function submit(){setBusy(true);setErr("");try{const x=await api(reg?"/api/auth/register":"/api/auth/login",{method:"POST",body:JSON.stringify(reg?{name,email,password}:{email,password})});localStorage.setItem("jarvis_token",x.token);location.href="/dashboard"}catch(e:any){setErr(e.message)}finally{setBusy(false)}}return <main className="auth-page"><div className="auth-card"><div className="auth-logo"><span className="brand-mark">J</span><div><b>JARVIS FOR ME</b><small>PERSONAL JEE OPERATING SYSTEM</small></div></div><span className="eyebrow">PRIVATE STUDENT WAR ROOM</span><h1>{reg?"Build your command center":"Welcome back, warrior."}</h1><p>Track study, backlog, practice, tests and your AI mentor in one place.</p>{reg&&<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/>}<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (6+ characters)"/>{err&&<div className="error">{err}</div>}<button className="primary full" onClick={submit} disabled={busy}>{busy?"Connecting…":reg?"Create JARVIS account":"Enter JARVIS"}</button><button className="switch" onClick={()=>setReg(!reg)}>{reg?"Already have an account? Log in":"New here? Create account"}</button></div></main>}
export function Gate({children,title,subtitle}:{children:ReactNode,title:string,subtitle:string}){const[ready,setReady]=useState(false),[auth,setAuth]=useState(false);useEffect(()=>{setAuth(!!localStorage.getItem("jarvis_token"));setReady(true)},[]);if(!ready)return <div className="loading">Starting JARVIS…</div>;if(!auth)return <Auth/>;return <Shell title={title} subtitle={subtitle}>{children}</Shell>}
export function Card({children,className=""}:{children:ReactNode,className?:string}){return <section className={"card "+className}>{children}</section>}
export function Stat({label,value,meta,icon}:{label:string,value:string|number,meta?:string,icon?:string}){return <div className="stat-card"><span className="stat-icon">{icon||"•"}</span><small>{label}</small><strong>{value}</strong>{meta&&<em>{meta}</em>}</div>}
export function SectionHead({kicker,title,action}:{kicker?:string,title:string,action?:ReactNode}){return <div className="section-head"><div>{kicker&&<span className="eyebrow">{kicker}</span>}<h2>{title}</h2></div>{action}</div>}
